export const questionBank = {
  aptitude: [
    {
      id: 'apt_001',
      question: 'A train travels 60 km in 1 hour. How long will it take to travel 210 km at the same speed?',
      difficulty: 'Easy',
      mode: 'Technical',
      keywords: ['3.5 hours', 'speed', 'distance', 'time', 'ratio', '210', 'divide', '60'],
      modelAnswer:
        'Speed = 60 km/h. Time = Distance ÷ Speed = 210 ÷ 60 = 3.5 hours. State the formula first, then substitute values.',
      tip: 'Always write the formula first, then substitute. Interviewers reward structured thinking.',
      strengthMsg: 'Good numerical reasoning shown.',
      improveMsg: 'State the formula explicitly. Use keywords: speed, distance, time.',
    },
    {
      id: 'apt_002',
      question: 'Tell me how you approach a timed aptitude section when you are running low on time.',
      difficulty: 'Medium',
      mode: 'HR',
      keywords: ['prioritize', 'easy', 'accuracy', 'skip', 'review', 'time', 'strategy', 'mark'],
      modelAnswer:
        'First I scan and solve high-accuracy easy questions. I skip lengthy puzzles, mark them, and return if time allows. I track time per block and avoid negative marking traps.',
      tip: 'Frame answer as a clear process: scan → prioritize → execute → review.',
      strengthMsg: 'Shows exam maturity and calm planning.',
      improveMsg: 'Mention skipping, review pass, and accuracy vs speed trade-off.',
    },
    {
      id: 'apt_003',
      question: 'If 20% of a number is 45, what is the number? Explain your method.',
      difficulty: 'Easy',
      mode: 'Technical',
      keywords: ['225', 'percent', '45', '100', 'equation', '0.2', 'divide', 'multiply'],
      modelAnswer: '20% of x = 45 → x = 45 ÷ 0.2 = 225. Alternatively: 45 is one-fifth, so full number = 45 × 5 = 225.',
      tip: 'Show two methods when possible — equation and fraction shortcut.',
      strengthMsg: 'Clear percentage conversion.',
      improveMsg: 'Include equation form and final number 225.',
    },
    {
      id: 'apt_004',
      question: 'Describe a situation where you improved your aptitude score through deliberate practice.',
      difficulty: 'Medium',
      mode: 'Behavioral',
      keywords: ['practice', 'mock', 'weak', 'topic', 'improved', 'analysis', 'daily', 'feedback'],
      modelAnswer:
        'I tracked weak topics after each mock, drilled one topic daily (e.g., percentages), and re-tested weekly. Score improved because I fixed root gaps, not random volume.',
      tip: 'Use STAR lightly: situation, action, measurable improvement.',
      strengthMsg: 'Demonstrates ownership and data-driven prep.',
      improveMsg: 'Add specific topic, mock tests, and measurable improvement.',
    },
    {
      id: 'apt_005',
      question: 'A shop offers 10% then 20% successive discount on ₹5000. What is the final price?',
      difficulty: 'Hard',
      mode: 'Technical',
      keywords: ['3600', 'successive', 'discount', 'multiply', '0.9', '0.8', '5000', 'percent'],
      modelAnswer:
        'Successive discounts multiply: 5000 × 0.9 × 0.8 = 3600. Do not add 10% + 20% — that is a common trap.',
      tip: 'Call out the trap: successive ≠ additive discounts.',
      strengthMsg: 'Correct successive discount logic.',
      improveMsg: 'Mention multiply factors and final price 3600.',
    },
    {
      id: 'apt_006',
      question: 'Why is aptitude important in campus placement interviews?',
      difficulty: 'Easy',
      mode: 'HR',
      keywords: ['filter', 'speed', 'accuracy', 'aptitude', 'screening', 'problem', 'thinking', 'baseline'],
      modelAnswer:
        'Aptitude screens analytical speed and accuracy at scale before technical rounds. It shows how you handle pressure, patterns, and quantitative decisions under time limits.',
      tip: 'Link aptitude to role readiness, not just exams.',
      strengthMsg: 'Connects aptitude to hiring goals.',
      improveMsg: 'Mention screening, speed, accuracy, and structured thinking.',
    },
    {
      id: 'apt_007',
      question: 'How do you verify an answer in data interpretation without a calculator?',
      difficulty: 'Hard',
      mode: 'Technical',
      keywords: ['estimate', 'round', 'ballpark', 'ratio', 'units', 'sanity', 'check', 'approximation'],
      modelAnswer:
        'I round values, compare ratios, and sanity-check units. If growth rate seems 200% on small base, I re-read axes and labels before confirming.',
      tip: 'Mention estimation, units, and graph traps.',
      strengthMsg: 'Shows verification discipline.',
      improveMsg: 'Include estimation, rounding, and sanity check keywords.',
    },
    {
      id: 'apt_008',
      question: 'What is your strategy for profit and loss questions in interviews?',
      difficulty: 'Medium',
      mode: 'Technical',
      keywords: ['cp', 'sp', 'profit', 'loss', 'percent', 'formula', 'cost price', 'selling'],
      modelAnswer:
        'I define CP and SP first, write profit% = (Profit/CP)×100, and draw a small table for multi-step markup/discount chains.',
      tip: 'Tables help for chained markup/discount problems.',
      strengthMsg: 'Structured CP/SP approach.',
      improveMsg: 'Use CP, SP, profit percent formula explicitly.',
    },
  ],
  verbal: [
    {
      id: 'ver_001',
      question: 'How do you approach a reading comprehension passage under time pressure?',
      difficulty: 'Medium',
      mode: 'Technical',
      keywords: ['skim', 'main idea', 'questions', 'passage', 'keywords', 'paragraph', 'inference', 'time'],
      modelAnswer:
        'Skim questions first, read for main idea and tone, underline keywords, then answer inference/detail items. I avoid re-reading the full passage twice.',
      tip: 'Question-first reading saves time in placements.',
      strengthMsg: 'Practical RC workflow.',
      improveMsg: 'Mention skim, main idea, and question-first strategy.',
    },
    {
      id: 'ver_002',
      question: 'Explain the difference between affect and effect with an example.',
      difficulty: 'Easy',
      mode: 'Technical',
      keywords: ['verb', 'noun', 'affect', 'effect', 'example', 'impact', 'influence', 'outcome'],
      modelAnswer:
        'Affect is usually a verb (influence): "Rain affects plans." Effect is usually a noun (result): "The effect was positive."',
      tip: 'Affect = Action (verb), Effect = End result (noun) — memory hook.',
      strengthMsg: 'Clear grammar distinction.',
      improveMsg: 'Include verb/noun roles and one example each.',
    },
    {
      id: 'ver_003',
      question: 'Tell me about a time you improved your English for professional communication.',
      difficulty: 'Medium',
      mode: 'Behavioral',
      keywords: ['reading', 'writing', 'practice', 'feedback', 'vocabulary', 'speaking', 'improved', 'daily'],
      modelAnswer:
        'I read editorials daily, summarized in my own words, and practiced concise email writing. Peer feedback on clarity helped me cut filler words.',
      tip: 'Behavioral answers need habit + outcome.',
      strengthMsg: 'Shows consistent habit-building.',
      improveMsg: 'Add daily habit, feedback, and communication outcome.',
    },
    {
      id: 'ver_004',
      question: 'What are common errors in subject-verb agreement?',
      difficulty: 'Easy',
      mode: 'Technical',
      keywords: ['singular', 'plural', 'subject', 'verb', 'agreement', 'each', 'neither', 'collective'],
      modelAnswer:
        'Match verb to true subject, not nearest noun. Watch "each/every/neither," collective nouns, and "there is/are" openings.',
      tip: 'Give 2–3 rule examples, not a lecture.',
      strengthMsg: 'Covers core SVA rules.',
      improveMsg: 'List each/every, collective nouns, and true subject rule.',
    },
    {
      id: 'ver_005',
      question: 'How would you correct: "The team are working on their project"?',
      difficulty: 'Medium',
      mode: 'Technical',
      keywords: ['team', 'singular', 'is', 'its', 'collective', 'american', 'british', 'agreement'],
      modelAnswer:
        'In US English: "The team is working on its project." Team is a collective singular. British English may use plural collectives.',
      tip: 'Mention US vs UK if asked in MNC interviews.',
      strengthMsg: 'Correct collective noun fix.',
      improveMsg: 'Include singular verb and pronoun its.',
    },
    {
      id: 'ver_006',
      question: 'Why do companies test verbal ability in placement drives?',
      difficulty: 'Easy',
      mode: 'HR',
      keywords: ['communication', 'email', 'client', 'documentation', 'clarity', 'professional', 'team', 'read'],
      modelAnswer:
        'Verbal skills predict how you read requirements, write emails, and explain ideas to clients and teammates. Errors in language can cause costly miscommunication.',
      tip: 'Tie verbal to workplace outcomes, not school grammar alone.',
      strengthMsg: 'Workplace-linked reasoning.',
      improveMsg: 'Mention communication, clarity, client, documentation.',
    },
    {
      id: 'ver_007',
      question: 'How do you tackle para-jumble questions?',
      difficulty: 'Hard',
      mode: 'Technical',
      keywords: ['mandatory', 'pair', 'opening', 'closing', 'connector', 'however', 'therefore', 'sequence'],
      modelAnswer:
        'Find opening/closing sentences, identify mandatory pairs, track connectors (however, therefore), then slot middle sentences by logic flow.',
      tip: 'Name connector words you hunt for.',
      strengthMsg: 'Logical PJ method.',
      improveMsg: 'Include opening/closing, pairs, and connector words.',
    },
    {
      id: 'ver_008',
      question: 'Describe how you build vocabulary without rote memorization.',
      difficulty: 'Medium',
      mode: 'Behavioral',
      keywords: ['context', 'roots', 'reading', 'usage', 'sentence', 'review', 'spaced', 'application'],
      modelAnswer:
        'I learn words in context from articles, note roots/prefixes, and use each new word in a sentence within 24 hours. Weekly review reinforces retention.',
      tip: 'Interviewers prefer application over mugging lists.',
      strengthMsg: 'Context-based learning approach.',
      improveMsg: 'Mention context, roots, and active usage.',
    },
  ],
  reasoning: [
    {
      id: 'rea_001',
      question: 'Explain your approach to solving a seating arrangement puzzle.',
      difficulty: 'Medium',
      mode: 'Technical',
      keywords: ['diagram', 'constraints', 'fixed', 'left', 'right', 'possibility', 'eliminate', 'step'],
      modelAnswer:
        'I list entities, draw a line/circle per puzzle type, place fixed constraints first, then propagate left/right relations and eliminate contradictions.',
      tip: 'Always mention diagram + fixed points first.',
      strengthMsg: 'Standard puzzle workflow.',
      improveMsg: 'Include diagram, constraints, and elimination.',
    },
    {
      id: 'rea_002',
      question: 'What is the difference between statement-conclusion and statement-assumption?',
      difficulty: 'Easy',
      mode: 'Technical',
      keywords: ['conclusion', 'assumption', 'implicit', 'follows', 'given', 'must', 'valid', 'logical'],
      modelAnswer:
        'Conclusion: what must follow from the statement. Assumption: what must be true for the statement to hold. Test with negation for assumptions.',
      tip: 'One-line distinction + tiny example wins marks.',
      strengthMsg: 'Clear conceptual split.',
      improveMsg: 'Define both and mention must follow vs implicit.',
    },
    {
      id: 'rea_003',
      question: 'How do you avoid silly mistakes in logical reasoning?',
      difficulty: 'Medium',
      mode: 'Behavioral',
      keywords: ['read twice', 'constraints', 'mark', 'check', 'rush', 'verify', 'diagram', 'calm'],
      modelAnswer:
        'I underline constraints, never assume unstated facts, redraw when stuck, and reserve 30 seconds to re-check the chain before locking an answer.',
      tip: 'Behavioral + process beats generic "I am careful."',
      strengthMsg: 'Concrete mistake-prevention habits.',
      improveMsg: 'Mention reread, constraints, and verification pass.',
    },
    {
      id: 'rea_004',
      question: 'Solve pattern: 2, 6, 12, 20, 30, ? — explain reasoning.',
      difficulty: 'Easy',
      mode: 'Technical',
      keywords: ['42', 'difference', 'increase', '2', '4', '6', '8', 'pattern'],
      modelAnswer: 'Differences: +4,+6,+8,+10 → next diff +12, so 30+12=42. Pattern: n(n+1) or add consecutive even increments.',
      tip: 'Show difference table — interviewers want method, not just 42.',
      strengthMsg: 'Difference method shown.',
      improveMsg: 'Include difference sequence and answer 42.',
    },
    {
      id: 'rea_005',
      question: 'When do you use Venn diagrams in reasoning tests?',
      difficulty: 'Medium',
      mode: 'Technical',
      keywords: ['venn', 'overlap', 'set', 'some', 'all', 'none', 'category', 'visual'],
      modelAnswer:
        'For syllogisms, category overlaps, and "some/all/none" problems — Venn diagrams make overlaps visible and reduce logical errors.',
      tip: 'Name problem types where Venn helps.',
      strengthMsg: 'Correct use cases.',
      improveMsg: 'Mention sets, overlap, some/all/none.',
    },
    {
      id: 'rea_006',
      question: 'Why is reasoning tested alongside aptitude?',
      difficulty: 'Easy',
      mode: 'HR',
      keywords: ['logic', 'decision', 'pattern', 'analytical', 'problem', 'structured', 'thinking', 'role'],
      modelAnswer:
        'Reasoning tests structured thinking beyond calculation — patterns, decisions, and consistency. Roles need logic for debugging, design, and trade-offs.',
      tip: 'Link to job tasks (debugging, analysis).',
      strengthMsg: 'Role-relevant justification.',
      improveMsg: 'Include logic, patterns, and decision-making.',
    },
    {
      id: 'rea_007',
      question: 'How would you explain syllogism validity to a non-technical friend?',
      difficulty: 'Hard',
      mode: 'Technical',
      keywords: ['premise', 'conclusion', 'must follow', 'all', 'some', 'no', 'valid', 'diagram'],
      modelAnswer:
        'Premises are given facts; conclusion must be forced by them. If conclusion only might be true, syllogism is invalid. Use Venn circles to test.',
      tip: 'Simple language + must follow rule.',
      strengthMsg: 'Clear teaching explanation.',
      improveMsg: 'Use premise, conclusion, must follow, Venn.',
    },
    {
      id: 'rea_008',
      question: 'Describe handling a puzzle you could not solve in the first 90 seconds.',
      difficulty: 'Hard',
      mode: 'Behavioral',
      keywords: ['skip', 'return', 'mark', 'time', 'partial', 'constraint', 'calm', 'strategy'],
      modelAnswer:
        'I note partial constraints, mark the question, move on to secure easy marks, then return with fresh eyes. Panic-solving wastes the whole section.',
      tip: 'Shows time management maturity.',
      strengthMsg: 'Smart exam strategy.',
      improveMsg: 'Mention skip, mark, return, and time box.',
    },
  ],
  technical: [
    {
      id: 'tec_001',
      question: 'Explain OOP pillars with a real-world analogy.',
      difficulty: 'Medium',
      mode: 'Technical',
      keywords: ['encapsulation', 'inheritance', 'polymorphism', 'abstraction', 'class', 'object', 'interface', 'example'],
      modelAnswer:
        'Encapsulation hides details (car dashboard). Inheritance reuses design (vehicle → car). Polymorphism: same action, different behavior. Abstraction: essential features only.',
      tip: 'One analogy per pillar keeps answer tight.',
      strengthMsg: 'Balanced OOP coverage.',
      improveMsg: 'Name all four pillars with brief examples.',
    },
    {
      id: 'tec_002',
      question: 'What is the difference between SQL and NoSQL databases?',
      difficulty: 'Easy',
      mode: 'Technical',
      keywords: ['relational', 'schema', 'document', 'scale', 'acid', 'flexible', 'join', 'mongodb'],
      modelAnswer:
        'SQL: tables, fixed schema, ACID, joins. NoSQL: flexible schema, horizontal scale, document/key-value models — trade consistency/joins for agility.',
      tip: 'Mention use cases: SQL for transactions, NoSQL for scale/flex.',
      strengthMsg: 'Correct trade-off framing.',
      improveMsg: 'Include schema, ACID, scale, and examples.',
    },
    {
      id: 'tec_003',
      question: 'Tell me about a technical concept you learned recently for placements.',
      difficulty: 'Medium',
      mode: 'Behavioral',
      keywords: ['learned', 'project', 'course', 'implemented', 'understand', 'practice', 'documentation', 'example'],
      modelAnswer:
        'Recently I deepened indexing in SQL — how B-tree indexes speed lookups and when over-indexing hurts writes. I tested queries with EXPLAIN on a sample schema.',
      tip: 'Pick one concept you can defend with an example.',
      strengthMsg: 'Shows continuous learning.',
      improveMsg: 'Name concept, how learned, and hands-on proof.',
    },
    {
      id: 'tec_004',
      question: 'Explain what a REST API is in simple terms.',
      difficulty: 'Easy',
      mode: 'Technical',
      keywords: ['http', 'get', 'post', 'resource', 'stateless', 'endpoint', 'json', 'client'],
      modelAnswer:
        'REST uses HTTP methods on resources (URLs). GET reads, POST creates, etc. Stateless: each request carries needed context. Usually JSON over HTTP.',
      tip: 'Mention methods + stateless + resources.',
      strengthMsg: 'Clear REST basics.',
      improveMsg: 'Include HTTP methods, stateless, JSON.',
    },
    {
      id: 'tec_005',
      question: 'What is time complexity and why does it matter?',
      difficulty: 'Medium',
      mode: 'Technical',
      keywords: ['big o', 'growth', 'input', 'efficient', 'algorithm', 'scale', 'worst', 'compare'],
      modelAnswer:
        'Time complexity describes how runtime grows with input size (Big-O). It matters for scale — O(n²) may fail large datasets while O(n log n) survives.',
      tip: 'Give one comparison example (linear vs quadratic).',
      strengthMsg: 'Shows algorithmic thinking.',
      improveMsg: 'Define Big-O and why scale matters.',
    },
    {
      id: 'tec_006',
      question: 'How do you stay updated with technology as a student?',
      difficulty: 'Easy',
      mode: 'HR',
      keywords: ['documentation', 'projects', 'community', 'newsletter', 'github', 'practice', 'course', 'consistent'],
      modelAnswer:
        'I follow official docs, build small projects, read release notes for tools I use, and contribute/learn on GitHub. Weekly learning block keeps it consistent.',
      tip: 'Credibility comes from habits, not listing 20 resources.',
      strengthMsg: 'Sustainable learning habits.',
      improveMsg: 'Mention docs, projects, and consistency.',
    },
    {
      id: 'tec_007',
      question: 'Difference between process and thread?',
      difficulty: 'Hard',
      mode: 'Technical',
      keywords: ['memory', 'context', 'switch', 'parallel', 'isolated', 'shared', 'cpu', 'lightweight'],
      modelAnswer:
        'Process: isolated memory space, heavier. Thread: lightweight unit within process, shares memory — faster context switch but needs sync for shared data.',
      tip: 'OS questions love memory isolation vs sharing.',
      strengthMsg: 'Core OS distinction correct.',
      improveMsg: 'Include isolation, shared memory, context switch.',
    },
    {
      id: 'tec_008',
      question: 'Walk through how you would debug a production issue.',
      difficulty: 'Hard',
      mode: 'Behavioral',
      keywords: ['reproduce', 'logs', 'isolate', 'hypothesis', 'fix', 'test', 'rollback', 'monitor'],
      modelAnswer:
        'Reproduce, check logs/metrics, isolate layer (API/DB/client), form hypothesis, fix with tests, deploy carefully, monitor and document postmortem.',
      tip: 'Order matters — shows senior mindset.',
      strengthMsg: 'Structured debugging flow.',
      improveMsg: 'List reproduce, logs, isolate, test, monitor.',
    },
  ],
  codelearning: [
    {
      id: 'code_001',
      question: 'How would you explain what a binary search tree is?',
      difficulty: 'Medium',
      mode: 'Technical',
      keywords: ['sorted', 'left', 'right', 'log n', 'search', 'insert', 'node', 'tree'],
      modelAnswer:
        'BST: left child smaller, right larger. Enables ordered walk and O(log n) search when balanced. Unbalanced tree degrades toward O(n).',
      tip: 'Mention ordering rule + complexity.',
      strengthMsg: 'Correct BST properties.',
      improveMsg: 'Include left/right rule and O(log n).',
    },
    {
      id: 'code_002',
      question: 'Tell me how you approach a new coding problem in an interview.',
      difficulty: 'Medium',
      mode: 'Behavioral',
      keywords: ['clarify', 'example', 'brute', 'optimize', 'edge', 'test', 'complexity', 'communicate'],
      modelAnswer:
        'Clarify constraints, work examples, propose brute force, optimize, discuss complexity, code cleanly, test edge cases aloud.',
      tip: 'This is the standard interview loop — memorize order.',
      strengthMsg: 'Interview process maturity.',
      improveMsg: 'Hit clarify, brute, optimize, edge cases.',
    },
    {
      id: 'code_003',
      question: 'What is the difference between array and linked list?',
      difficulty: 'Easy',
      mode: 'Technical',
      keywords: ['index', 'memory', 'insert', 'delete', 'pointer', 'contiguous', 'random', 'access'],
      modelAnswer:
        'Array: contiguous, O(1) index access, costly middle insert. Linked list: nodes with pointers, O(n) access, cheap inserts if pointer known.',
      tip: 'Trade-offs, not "one is better."',
      strengthMsg: 'Balanced comparison.',
      improveMsg: 'Mention access, insert cost, memory layout.',
    },
    {
      id: 'code_004',
      question: 'Why is coding round important if I already have good CGPA?',
      difficulty: 'Easy',
      mode: 'HR',
      keywords: ['implementation', 'logic', 'real', 'problem', 'skill', 'practice', 'team', 'delivery'],
      modelAnswer:
        'CGPA shows academics; coding shows you can implement logic under pressure — closer to daily engineering work than theory exams alone.',
      tip: 'Respectful tone — don’t dismiss CGPA.',
      strengthMsg: 'Balanced, professional view.',
      improveMsg: 'Contrast academics vs implementation skill.',
    },
    {
      id: 'code_005',
      question: 'Explain recursion with an example and one risk.',
      difficulty: 'Medium',
      mode: 'Technical',
      keywords: ['base case', 'stack', 'overflow', 'function', 'calls itself', 'factorial', 'tree', 'terminate'],
      modelAnswer:
        'Function solves smaller sub-instances until base case (e.g., factorial). Risk: stack overflow without base case or too deep recursion.',
      tip: 'Always mention base case + stack overflow.',
      strengthMsg: 'Recursion defined with risk.',
      improveMsg: 'Include base case and stack overflow.',
    },
    {
      id: 'code_006',
      question: 'How do you test your code before submission?',
      difficulty: 'Medium',
      mode: 'Behavioral',
      keywords: ['sample', 'edge', 'empty', 'boundary', 'dry run', 'unit', 'case', 'verify'],
      modelAnswer:
        'I run sample inputs, edge cases (empty, single, max), dry-run loops for off-by-one, and check return type/format matches spec.',
      tip: 'List 3 edge types interviewers love.',
      strengthMsg: 'Solid testing discipline.',
      improveMsg: 'Mention edge cases and dry run.',
    },
    {
      id: 'code_007',
      question: 'What is dynamic programming in one minute?',
      difficulty: 'Hard',
      mode: 'Technical',
      keywords: ['overlapping', 'subproblem', 'memoization', 'tabulation', 'optimal', 'reuse', 'cache', 'dp'],
      modelAnswer:
        'DP breaks problems into overlapping subproblems, stores results (memo/tabulation) to avoid recomputation, typically for optimization/counting problems.',
      tip: 'Keywords: overlapping subproblems + memoization.',
      strengthMsg: 'DP essence captured.',
      improveMsg: 'Use overlapping, memoization, optimal.',
    },
    {
      id: 'code_008',
      question: 'Describe a bug you fixed that taught you something important.',
      difficulty: 'Hard',
      mode: 'Behavioral',
      keywords: ['bug', 'cause', 'fix', 'test', 'learned', 'root', 'prevent', 'debug'],
      modelAnswer:
        'I had an off-by-one loop causing wrong output on boundary input. Fixed bounds, added test case, learned to always test min/max edges before submit.',
      tip: 'End with lesson learned — interviewers remember that line.',
      strengthMsg: 'Growth-oriented story.',
      improveMsg: 'Include cause, fix, and lesson.',
    },
  ],
  interviewquestion: [
    {
      id: 'int_001',
      question: 'Tell me about yourself — structure a 60-second placement answer.',
      difficulty: 'Easy',
      mode: 'HR',
      keywords: ['education', 'skills', 'project', 'internship', 'goal', 'role', 'brief', 'strength'],
      modelAnswer:
        'Present → past academics → 2 strengths → 1 project/internship highlight → why this role/company. Keep under 60 seconds, no life story.',
      tip: 'Formula: Present → Past → Future (role fit).',
      strengthMsg: 'Structured self-intro.',
      improveMsg: 'Include education, project, and role goal.',
    },
    {
      id: 'int_002',
      question: 'What are your strengths and weaknesses? (with weakness recovery)',
      difficulty: 'Medium',
      mode: 'HR',
      keywords: ['strength', 'weakness', 'improving', 'example', 'honest', 'action', 'feedback', 'growth'],
      modelAnswer:
        'Strength with proof. Weakness: real but safe (e.g., public speaking), plus actions taken to improve. Never say "I have no weaknesses."',
      tip: 'Weakness must show improvement plan.',
      strengthMsg: 'Balanced, credible answer.',
      improveMsg: 'Add example and improvement plan for weakness.',
    },
    {
      id: 'int_003',
      question: 'Explain a project from your resume in STAR format.',
      difficulty: 'Medium',
      mode: 'Behavioral',
      keywords: ['situation', 'task', 'action', 'result', 'tech', 'impact', 'team', 'metric'],
      modelAnswer:
        'Situation/Task in one line each. Action: your specific contributions and stack. Result: metric (users, time saved, accuracy).',
      tip: 'Quantify result whenever possible.',
      strengthMsg: 'STAR structure present.',
      improveMsg: 'Include situation, action, measurable result.',
    },
    {
      id: 'int_004',
      question: 'Why should we hire you over other candidates?',
      difficulty: 'Medium',
      mode: 'HR',
      keywords: ['fit', 'skills', 'learn', 'attitude', 'delivery', 'team', 'evidence', 'role'],
      modelAnswer:
        'Match role needs with 2–3 evidences: relevant skills, project proof, learning speed, and teamwork. Avoid comparing others negatively.',
      tip: 'Evidence-based, not generic "I am hardworking."',
      strengthMsg: 'Role-aligned pitch.',
      improveMsg: 'Tie skills to role with evidence.',
    },
    {
      id: 'int_005',
      question: 'Where do you see yourself in five years?',
      difficulty: 'Easy',
      mode: 'HR',
      keywords: ['grow', 'engineer', 'skills', 'contribute', 'company', 'learning', 'responsibility', 'realistic'],
      modelAnswer:
        'Grow as a strong engineer in the company — deeper technical ownership, mentoring juniors, delivering business impact. Avoid "CEO in 2 years."',
      tip: 'Show loyalty and skill growth, not job hopping.',
      strengthMsg: 'Realistic growth path.',
      improveMsg: 'Mention skill growth and contribution.',
    },
    {
      id: 'int_006',
      question: 'Describe a conflict in a team project and how you resolved it.',
      difficulty: 'Hard',
      mode: 'Behavioral',
      keywords: ['listen', 'communicate', 'compromise', 'goal', 'respect', 'resolve', 'team', 'outcome'],
      modelAnswer:
        'Acknowledge views, refocus on project goal, propose data-driven decision or split tasks by strength, follow up to ensure harmony.',
      tip: 'No blame — show maturity.',
      strengthMsg: 'Mature conflict handling.',
      improveMsg: 'Include listen, goal focus, resolution outcome.',
    },
    {
      id: 'int_007',
      question: 'What is difference between abstract class and interface in Java?',
      difficulty: 'Medium',
      mode: 'Technical',
      keywords: ['abstract', 'interface', 'multiple', 'inheritance', 'default', 'method', 'state', 'implement'],
      modelAnswer:
        'Abstract class: partial implementation, single inheritance, can have state. Interface: contract, multiple implementation, default/static methods since Java 8.',
      tip: 'Java-specific — align with interview-question subject.',
      strengthMsg: 'Correct Java OOP distinction.',
      improveMsg: 'Mention inheritance limits and state.',
    },
    {
      id: 'int_008',
      question: 'Do you have any questions for us?',
      difficulty: 'Easy',
      mode: 'HR',
      keywords: ['team', 'onboarding', 'projects', 'growth', 'culture', 'role', 'learning', 'expectations'],
      modelAnswer:
        'Ask about team structure, onboarding, technologies used, success metrics for the role, and growth paths. Avoid salary in first round unless prompted.',
      tip: 'Prepare 2 questions — shows genuine interest.',
      strengthMsg: 'Thoughtful interviewer questions.',
      improveMsg: 'Ask about team, role, growth — specific.',
    },
  ],
  companywiseprep: [
    {
      id: 'com_001',
      question: 'Why do you want to join TCS / service-based companies?',
      difficulty: 'Easy',
      mode: 'HR',
      keywords: ['learning', 'scale', 'projects', 'clients', 'stability', 'training', 'career', 'exposure'],
      modelAnswer:
        'Large client exposure, structured training, diverse projects, and long-term career paths. I want to build fundamentals before specializing.',
      tip: 'Company-agnostic template — customize company name.',
      strengthMsg: 'Shows research and fit.',
      improveMsg: 'Mention learning, scale, and career path.',
    },
    {
      id: 'com_002',
      question: 'How do you prepare differently for product vs service companies?',
      difficulty: 'Medium',
      mode: 'HR',
      keywords: ['dsa', 'system design', 'aptitude', 'communication', 'role', 'research', 'company', 'focus'],
      modelAnswer:
        'Product: heavier DSA + system design + depth in stack. Service: aptitude, communication, fundamentals, flexibility across technologies.',
      tip: 'Shows strategic preparation.',
      strengthMsg: 'Clear prep differentiation.',
      improveMsg: 'Contrast product vs service focus areas.',
    },
    {
      id: 'com_003',
      question: 'Explain a company-specific requirement: willingness to relocate.',
      difficulty: 'Easy',
      mode: 'HR',
      keywords: ['relocate', 'flexible', 'opportunity', 'family', 'discuss', 'yes', 'locations', 'travel'],
      modelAnswer:
        'Yes, I am open to relocation for the right project and growth. I will discuss logistics early and ensure smooth transition.',
      tip: 'Be clear if true — honesty matters.',
      strengthMsg: 'Direct, professional reply.',
      improveMsg: 'State flexibility and positive framing.',
    },
    {
      id: 'com_004',
      question: 'What do you know about our company’s interview pattern?',
      difficulty: 'Medium',
      mode: 'Technical',
      keywords: ['aptitude', 'technical', 'hr', 'rounds', 'coding', 'communication', 'group', 'discussion'],
      modelAnswer:
        'Typically aptitude/reasoning screen, technical + coding, managerial/HR. I practiced company PYQs and mock interviews for each round type.',
      tip: 'Mention you researched — cite rounds.',
      strengthMsg: 'Preparation awareness.',
      improveMsg: 'List round types and prep actions.',
    },
    {
      id: 'com_005',
      question: 'How would you handle being placed on a technology you did not choose?',
      difficulty: 'Medium',
      mode: 'Behavioral',
      keywords: ['adapt', 'learn', 'positive', 'basics', 'contribute', 'attitude', 'quick', 'master'],
      modelAnswer:
        'Accept assignment, ramp quickly on fundamentals, seek mentors, deliver on small tasks first, then deepen expertise — attitude matters more than initial preference.',
      tip: 'Service companies love adaptable mindset.',
      strengthMsg: 'Adaptability shown.',
      improveMsg: 'Include learn, adapt, contribute.',
    },
    {
      id: 'com_006',
      question: 'Describe how you use company-wise prep resources effectively.',
      difficulty: 'Easy',
      mode: 'Behavioral',
      keywords: ['pyq', 'pattern', 'topics', 'mock', 'weak', 'track', 'revision', 'schedule'],
      modelAnswer:
        'I study PYQ patterns, list recurring topics, schedule mocks, and revise weak areas weekly instead of random solving.',
      tip: 'Tie to your platform’s company prep feature.',
      strengthMsg: 'Structured resource usage.',
      improveMsg: 'Mention PYQ, patterns, mocks, tracking.',
    },
    {
      id: 'com_007',
      question: 'Technical: Explain testing and why companies expect it.',
      difficulty: 'Hard',
      mode: 'Technical',
      keywords: ['unit', 'integration', 'quality', 'bug', 'regression', 'automate', 'ci', 'reliable'],
      modelAnswer:
        'Testing verifies behavior, prevents regressions, improves reliability. Levels: unit (functions), integration (modules), E2E (flows). CI runs tests on each change.',
      tip: 'Connect testing to business risk reduction.',
      strengthMsg: 'Testing value articulated.',
      improveMsg: 'Include unit, integration, regression, CI.',
    },
    {
      id: 'com_008',
      question: 'How do you manage stress during multi-round placement week?',
      difficulty: 'Hard',
      mode: 'Behavioral',
      keywords: ['sleep', 'plan', 'break', 'hydrate', 'mock', 'positive', 'schedule', 'recover'],
      modelAnswer:
        'Fixed sleep, daily plan per company, short breaks between drives, debrief after each round without dwelling, light exercise to reset focus.',
      tip: 'Wellness + planning shows maturity.',
      strengthMsg: 'Healthy coping strategies.',
      improveMsg: 'Mention plan, rest, debrief, recovery.',
    },
  ],
  companypyq: [
    {
      id: 'pyq_001',
      question: 'How do you analyze a company PYQ paper before practicing?',
      difficulty: 'Medium',
      mode: 'Technical',
      keywords: ['pattern', 'topic', 'frequency', 'difficulty', 'year', 'trend', 'weightage', 'analyze'],
      modelAnswer:
        'Group questions by topic, note repeating patterns and difficulty trend by year, prioritize high-frequency topics, then timed mocks.',
      tip: 'Analysis before volume solving saves time.',
      strengthMsg: 'Strategic PYQ approach.',
      improveMsg: 'Include pattern, frequency, prioritization.',
    },
    {
      id: 'pyq_002',
      question: 'A PYQ states: "All cats are animals. Some animals are pets." What can you conclude?',
      difficulty: 'Hard',
      mode: 'Technical',
      keywords: ['syllogism', 'some', 'cannot', 'definite', 'pets', 'cats', 'conclusion', 'venn'],
      modelAnswer:
        'Only definite: some animals are pets. You cannot conclude all cats are pets or some cats are pets without additional premises. Draw Venn to verify.',
      tip: 'PYQ reasoning often tests invalid conclusions.',
      strengthMsg: 'Careful logical conclusion.',
      improveMsg: 'State what cannot be concluded; use Venn.',
    },
    {
      id: 'pyq_003',
      question: 'Why is practicing PYQs better than only reading theory?',
      difficulty: 'Easy',
      mode: 'HR',
      keywords: ['pattern', 'time', 'exam', 'real', 'confidence', 'gap', 'application', 'practice'],
      modelAnswer:
        'PYQs expose real patterns, time pressure, and recurring traps. Theory alone misses how a company actually asks questions.',
      tip: 'Link to exam authenticity.',
      strengthMsg: 'Practice-oriented mindset.',
      improveMsg: 'Mention patterns, time, real exam.',
    },
    {
      id: 'pyq_004',
      question: 'How do you avoid memorizing PYQ answers without understanding?',
      difficulty: 'Medium',
      mode: 'Behavioral',
      keywords: ['concept', 'variation', 'explain', 'why', 'derive', 'similar', 'understand', 'solve'],
      modelAnswer:
        'After each PYQ I solve from scratch again, explain steps aloud, and attempt a variation with changed numbers/constraints.',
      tip: 'Shows intellectual honesty.',
      strengthMsg: 'Deep learning habit.',
      improveMsg: 'Include re-solve, explain, variation.',
    },
    {
      id: 'pyq_005',
      question: 'Technical PYQ: What is output of 5 + "5" in JavaScript?',
      difficulty: 'Easy',
      mode: 'Technical',
      keywords: ['55', 'concatenation', 'string', 'number', 'coercion', 'type', 'javascript', 'plus'],
      modelAnswer: 'Result is "55" — number 5 coerces to string, + concatenates. Use Number() or parseInt for arithmetic.',
      tip: 'Type coercion is common in PYQ tech snippets.',
      strengthMsg: 'Correct JS coercion.',
      improveMsg: 'Say 55, concatenation, coercion.',
    },
    {
      id: 'pyq_006',
      question: 'Describe your PYQ revision schedule one week before drive.',
      difficulty: 'Medium',
      mode: 'Behavioral',
      keywords: ['revision', 'mock', 'weak', 'formula', 'flashcard', 'timed', 'sleep', 'company'],
      modelAnswer:
        'Day 1–2: high-weightage topics. Day 3–4: timed PYQ mocks. Day 5: weak-area drill. Day 6: light revision + rest. Day 7: logistics only.',
      tip: 'Concrete schedule impresses HR panels too.',
      strengthMsg: 'Actionable revision plan.',
      improveMsg: 'Give day-wise structure.',
    },
    {
      id: 'pyq_007',
      question: 'How do you handle a PYQ question you have never seen before?',
      difficulty: 'Hard',
      mode: 'Behavioral',
      keywords: ['calm', 'break down', 'known', 'eliminate', 'guess', 'logic', 'partial', 'time'],
      modelAnswer:
        'Stay calm, break into sub-parts, use elimination and analogies to known patterns, secure partial logic marks, don’t over-invest time.',
      tip: 'Partial credit mindset helps in exams.',
      strengthMsg: 'Composed unknown-question strategy.',
      improveMsg: 'Mention break down, eliminate, time limit.',
    },
    {
      id: 'pyq_008',
      question: 'What metrics do you track after each PYQ mock test?',
      difficulty: 'Medium',
      mode: 'Technical',
      keywords: ['accuracy', 'time', 'topic', 'wrong', 'speed', 'improvement', 'score', 'review'],
      modelAnswer:
        'Accuracy %, time per section, top 3 weak topics, silly vs concept errors, and delta vs previous mock.',
      tip: 'Data-driven improvement story.',
      strengthMsg: 'Metrics-aware prep.',
      improveMsg: 'List accuracy, time, weak topics, errors.',
    },
  ],
  projects: [
    {
      id: 'pro_001',
      question: 'Walk me through your best project in 90 seconds.',
      difficulty: 'Medium',
      mode: 'Behavioral',
      keywords: ['problem', 'stack', 'role', 'feature', 'result', 'user', 'tech', 'impact'],
      modelAnswer:
        'Problem → your role → stack → 2 key features → outcome (users/metrics). End with what you would improve next.',
      tip: '90 seconds max — practice with timer.',
      strengthMsg: 'Concise project pitch.',
      improveMsg: 'Include problem, stack, role, result.',
    },
    {
      id: 'pro_002',
      question: 'What technical challenges did you face in a project and how did you solve them?',
      difficulty: 'Hard',
      mode: 'Technical',
      keywords: ['challenge', 'debug', 'research', 'solution', 'learned', 'api', 'database', 'performance'],
      modelAnswer:
        'State one specific challenge (e.g., slow API), debugging steps, solution (caching/indexing), and measurable improvement.',
      tip: 'One deep story beats three shallow ones.',
      strengthMsg: 'Technical depth shown.',
      improveMsg: 'Specific challenge + solution + metric.',
    },
    {
      id: 'pro_003',
      question: 'How do you choose a project for your resume?',
      difficulty: 'Easy',
      mode: 'HR',
      keywords: ['relevance', 'complete', 'deploy', 'demo', 'stack', 'role', 'impact', 'maintainable'],
      modelAnswer:
        'Pick projects aligned to target role, finished enough to demo/deploy, where you owned clear modules, and can explain design trade-offs.',
      tip: 'Quality > quantity on resume.',
      strengthMsg: 'Resume strategy clear.',
      improveMsg: 'Mention relevance, demo, ownership.',
    },
    {
      id: 'pro_004',
      question: 'Explain Git workflow you used in a team project.',
      difficulty: 'Medium',
      mode: 'Technical',
      keywords: ['branch', 'pull request', 'merge', 'commit', 'main', 'review', 'conflict', 'git'],
      modelAnswer:
        'Feature branches off main, small commits, PR with review, resolve conflicts locally, merge after CI/checks pass.',
      tip: 'Mention PR review — industry standard.',
      strengthMsg: 'Collaborative Git flow.',
      improveMsg: 'Include branch, PR, review, merge.',
    },
    {
      id: 'pro_005',
      question: 'If you had one more month on your project, what would you improve?',
      difficulty: 'Medium',
      mode: 'HR',
      keywords: ['test', 'security', 'performance', 'ui', 'documentation', 'scale', 'refactor', 'monitor'],
      modelAnswer:
        'Add automated tests, security hardening, performance profiling, better docs, and monitoring — shows product thinking beyond MVP.',
      tip: 'Shows vision without dismissing current work.',
      strengthMsg: 'Forward-looking improvement plan.',
      improveMsg: 'Name 2–3 concrete improvements.',
    },
    {
      id: 'pro_006',
      question: 'How do you explain a project to a non-technical interviewer?',
      difficulty: 'Easy',
      mode: 'HR',
      keywords: ['simple', 'analogy', 'benefit', 'user', 'business', 'avoid jargon', 'outcome', 'problem'],
      modelAnswer:
        'Focus on user problem and business benefit, use analogies, avoid jargon, mention outcome metrics — invite questions on tech only if asked.',
      tip: 'HR round ≠ deep code walkthrough.',
      strengthMsg: 'Audience-aware communication.',
      improveMsg: 'User benefit, simple language, outcome.',
    },
    {
      id: 'pro_007',
      question: 'What is the difference between frontend and backend in your project?',
      difficulty: 'Easy',
      mode: 'Technical',
      keywords: ['ui', 'api', 'server', 'client', 'database', 'react', 'node', 'separation'],
      modelAnswer:
        'Frontend: UI users see (React/HTML). Backend: APIs, business logic, database. They communicate via HTTP/JSON with clear separation of concerns.',
      tip: 'Mention API boundary between them.',
      strengthMsg: 'Clear architecture split.',
      improveMsg: 'Define UI vs server/API/database.',
    },
    {
      id: 'pro_008',
      question: 'Describe a time you had to learn a new tool mid-project.',
      difficulty: 'Hard',
      mode: 'Behavioral',
      keywords: ['document', 'tutorial', 'prototype', 'deadline', 'deliver', 'learn', 'quick', 'apply'],
      modelAnswer:
        'Needed Docker for deployment — read docs, built hello-world prototype in a day, applied to project, asked teammate for review before production use.',
      tip: 'Show fast, safe learning under deadline.',
      strengthMsg: 'Adaptive learning story.',
      improveMsg: 'Tool name, learning steps, delivery.',
    },
  ],
}

export const getQuestionsForSubject = (coachSubjectId) =>
  questionBank[coachSubjectId] ?? []
